---
apiVersion: v1
kind: Service
metadata:
  name: mutateme
  labels:
    app: mutateme
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: mutateme

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutateme
  labels:
    app: mutateme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutateme
  template:
    metadata:
      name: mutateme
      labels:
        app: mutateme
    spec:
      containers:
        - name: mutator
          image: localhost:5000/alexleonhardt/k8s-mutate-webhook:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutateme
  labels:
    app: mutateme
webhooks:
  - name: mutateme.default.svc.cluster.local
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1ESXlNekl5TURjek4xb1hEVE14TURJeU1USXlNRGN6TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTExNCnV6Zm9sSHc5RGJxQi83MkNrZlVPRGVJQzMyZkRrb3M3UXZyMDczMWpVbCtpVFVGZUc3em5hRno3MEQrYVh1SkUKSWt6NVhzcEgzWkI5T1hlL25NaXlIM0U0UE9LYlhtbjVYV0RoMTcvMXlxT2NuUkZvODluVS9pTVh3VXFSMHhSbQpNeHZvSnB2L1drcVc4a2ZibjVoT0s0dnpDbHlKeUJRNC9yeTNocTl5clNtWllRQkxFSmZVTXg5UlU2dkl0bmhMCk5HSlBYZ2xTdktOWFMyZmY4QVd2R25pRzlKbkFucExPL3NEM3Q4VzQvcTk4ejh4a1JXSnVvYVNHaFZ1OUIzaXoKdnU0a1M1dmRqT3oyNzZsOFFGRnVkVExaSkJBL1k5eHZiV3RmOGFKK2pFY3U5N1Bva2hRY09wTzFNOGdvWG1iMQovbDV6SFlqTHkrRytsVkxySnU4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNbE9kWjZYVmNVR0xDeThjb0ZheHVNcTRGZUZNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBbHplZ3JlazVGd01CVE1pRTdTZmJOa2l3amtGVDBNSkhVcXhKekZ1b1BydC9NSUh1Kwp6cFRIdlU4dXh6ak4wODNTMElUWUNqWno4RUh2N25kZlh1RUlEaHdXOWJ5WGxKTGVVQVR4ZysyMHp2MWJ2N1B5CitCeUVzYWxDSFNVL3VuWFZaakZhSFU2TTlKb1E2WFprdVdOWUVSVG5BT0U4Tld1aTRDRWQvcE9wWm5CdnRlY2QKK0RZTTcxam5GZElPNEFUc0FSZU56WFBtWXM1RERCT0NqNVNxbkRmSUNqNjB1a3loY1RqbnZpbkQrUmUxYlVUZgpoeWhDS1RUajREUlUvcTVwc3B5dUljQ2VMRW5VOFJPMHF1ZE9rSW5tNmZwYk1Xd1JzU0oxS2NrbFpiMTdBaU9MCk9Jc2hZb21hcGxudytzNGRUUzBmSUFIMnJORHptT1RuYjJ3cwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: mutateme
        namespace: default
        path: "/mutate"
        port: 443
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        mutateme: enabled
